// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function Chat(arg1:string,arg2:string,arg3:Array<main.ChatMessage>,arg4:main.ChatOptions):Promise<main.ChatResponse>;

export function Greet(arg1:string):Promise<string>;

export function Models(arg1:string):Promise<Array<string>>;

export function OpenPath(arg1:string):Promise<void>;

export function OutputDir():Promise<string>;

export function Providers():Promise<Array<string>>;

export function RespondPermission(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function StreamAgent(arg1:string,arg2:string,arg3:string,arg4:Array<main.ChatMessage>,arg5:main.ChatOptions,arg6:Array<string>,arg7:Array<string>):Promise<void>;

export function StreamChat(arg1:string,arg2:string,arg3:string,arg4:Array<main.ChatMessage>,arg5:main.ChatOptions):Promise<void>;

export function Tools():Promise<Array<string>>;
