// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function Chat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Chat'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Models(arg1) {
  return window['go']['main']['App']['Models'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OutputDir() {
  return window['go']['main']['App']['OutputDir']();
}

export function Providers() {
  return window['go']['main']['App']['Providers']();
}

export function RespondPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2, arg3);
}

export function StreamAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StreamAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StreamChat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StreamChat'](arg1, arg2, arg3, arg4, arg5);
}

export function Tools() {
  return window['go']['main']['App']['Tools']();
}
