// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function Chat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Chat'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteChatAttachments(arg1) {
  return window['go']['main']['App']['DeleteChatAttachments'](arg1);
}

export function DeleteKnowledgeSource(arg1, arg2) {
  return window['go']['main']['App']['DeleteKnowledgeSource'](arg1, arg2);
}

export function ExportChatMarkdown(arg1) {
  return window['go']['main']['App']['ExportChatMarkdown'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IndexPath(arg1, arg2) {
  return window['go']['main']['App']['IndexPath'](arg1, arg2);
}

export function KnowledgeSources(arg1) {
  return window['go']['main']['App']['KnowledgeSources'](arg1);
}

export function LoadAttachment(arg1) {
  return window['go']['main']['App']['LoadAttachment'](arg1);
}

export function Models(arg1) {
  return window['go']['main']['App']['Models'](arg1);
}

export function ModelsCatalog() {
  return window['go']['main']['App']['ModelsCatalog']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OutputDir() {
  return window['go']['main']['App']['OutputDir']();
}

export function PickKnowledgePath(arg1) {
  return window['go']['main']['App']['PickKnowledgePath'](arg1);
}

export function PickWorkspaceDir() {
  return window['go']['main']['App']['PickWorkspaceDir']();
}

export function Providers() {
  return window['go']['main']['App']['Providers']();
}

export function RespondPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2, arg3);
}

export function SaveAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2, arg3, arg4);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function StartupWorkspaceDir() {
  return window['go']['main']['App']['StartupWorkspaceDir']();
}

export function StreamAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['StreamAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function StreamChat(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StreamChat'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Tools() {
  return window['go']['main']['App']['Tools']();
}

export function ToolsMetadata() {
  return window['go']['main']['App']['ToolsMetadata']();
}
