// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1, arg2) {
  return window['go']['main']['App']['Ask'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Providers() {
  return window['go']['main']['App']['Providers']();
}
