// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';
import {margo} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function Chat(arg1:string,arg2:string,arg3:Array<main.ChatMessage>,arg4:main.ChatOptions,arg5:Array<main.AttachmentInput>):Promise<main.ChatResponse>;

export function DeleteChatAttachments(arg1:string):Promise<void>;

export function DeleteKnowledgeSource(arg1:string,arg2:string):Promise<void>;

export function ExportChatMarkdown(arg1:core.ChatExport):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IndexPath(arg1:string,arg2:string):Promise<core.IndexResult>;

export function KnowledgeSources(arg1:string):Promise<Array<core.KnowledgeSource>>;

export function LoadAttachment(arg1:string):Promise<string>;

export function Models(arg1:string):Promise<Array<string>>;

export function ModelsCatalog():Promise<margo.Catalog>;

export function OpenPath(arg1:string):Promise<void>;

export function OutputDir():Promise<string>;

export function PickKnowledgePath(arg1:boolean):Promise<string>;

export function PickWorkspaceDir():Promise<string>;

export function Providers():Promise<Array<string>>;

export function RespondPermission(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SaveAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<core.StoredAttachment>;

export function SetActiveWorkspace(arg1:string):Promise<void>;

export function StartupWorkspaceDir():Promise<string>;

export function StreamAgent(arg1:string,arg2:string,arg3:string,arg4:Array<main.ChatMessage>,arg5:main.ChatOptions,arg6:Array<string>,arg7:Array<string>,arg8:Array<main.AttachmentInput>,arg9:string):Promise<void>;

export function StreamChat(arg1:string,arg2:string,arg3:string,arg4:Array<main.ChatMessage>,arg5:main.ChatOptions,arg6:Array<main.AttachmentInput>):Promise<void>;

export function Tools():Promise<Array<string>>;

export function ToolsMetadata():Promise<Array<core.ToolMetadata>>;
